// watson
export const FETCH_WATSON = 'FETCH_WATSON';
export const FETCH_WATSON_SUCCESS = 'FETCH_WATSON_SUCCESS';
export const FETCH_WATSON_FAILURE = 'FETCH_WATSON_FAILURE';

// yelp
export const FETCH_YELP = 'FETCH_YELP';
export const FETCH_YELP_SUCCESS = 'FETCH_YELP_SUCCESS';
export const FETCH_YELP_FAILURE = 'FETCH_YELP_FAILURE';
