export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';
export const REGISTER_SEARCH_TERM = 'REGISTER_SEARCH_TERM';
export const EXECUTE_SEARCH = 'EXECUTE_SEARCH';
// watson
export const FETCH_WATSON = 'FETCH_WATSON';
export const FETCH_WATSON_SUCCESS = 'FETCH_WATSON_SUCCESS';
export const FETCH_WATSON_FAILURE = 'FETCH_WATSON_FAILURE';
